function [ ma1 ] = tubiao( sortresult )
%做出图表，分图
%   调用示例：[ para ] = tubiao( sortresult );
%% 年度数据
%ma=sortresult.vlm.table.ma.cum{1,2};
%bah=sortresult.vlm.table.bah.cum{1,2};
%xlabel = [2003:2014]';
%plot(xlabel,ma);
ma1=[];
bah1=[];
%%  vlm日数据
para =1;
ma1=sortresult.vlm.table.ma.cum{para,1};
bah1=sortresult.vlm.table.bah.cum{para,1};
ma2=sortresult.vlm.table.ma.cum{para,2};
bah2=sortresult.vlm.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,1);
plot(xlabel,bah2,xlabel,ma2);
para =2;
ma1=sortresult.vlm.table.ma.cum{para,1};
bah1=sortresult.vlm.table.bah.cum{para,1};
ma2=sortresult.vlm.table.ma.cum{para,2};
bah2=sortresult.vlm.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,2);
plot(xlabel,bah2,xlabel,ma2);
para =3;
ma1=sortresult.vlm.table.ma.cum{para,1};
bah1=sortresult.vlm.table.bah.cum{para,1};
ma2=sortresult.vlm.table.ma.cum{para,2};
bah2=sortresult.vlm.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,3);
plot(xlabel,bah2,xlabel,ma2);
%% openinst
para =1;
ma1=sortresult.openinst.table.ma.cum{para,1};
bah1=sortresult.openinst.table.bah.cum{para,1};
ma2=sortresult.openinst.table.ma.cum{para,2};
bah2=sortresult.openinst.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,4);
plot(xlabel,bah2,xlabel,ma2);
para =2;
ma1=sortresult.openinst.table.ma.cum{para,1};
bah1=sortresult.openinst.table.bah.cum{para,1};
ma2=sortresult.openinst.table.ma.cum{para,2};
bah2=sortresult.openinst.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,5);
plot(xlabel,bah2,xlabel,ma2);
para =3;
ma1=sortresult.openinst.table.ma.cum{para,1};
bah1=sortresult.openinst.table.bah.cum{para,1};
ma2=sortresult.openinst.table.ma.cum{para,2};
bah2=sortresult.openinst.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,6);
plot(xlabel,bah2,xlabel,ma2);
%% vltlt
para =1;
ma1=sortresult.vltlt.table.ma.cum{para,1};
bah1=sortresult.vltlt.table.bah.cum{para,1};
ma2=sortresult.vltlt.table.ma.cum{para,2};
bah2=sortresult.vltlt.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,7);
plot(xlabel,bah2,xlabel,ma2);
para =2;
ma1=sortresult.vltlt.table.ma.cum{para,1};
bah1=sortresult.vltlt.table.bah.cum{para,1};
ma2=sortresult.vltlt.table.ma.cum{para,2};
bah2=sortresult.vltlt.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,8);
plot(xlabel,bah2,xlabel,ma2);
para =3;
ma1=sortresult.vltlt.table.ma.cum{para,1};
bah1=sortresult.vltlt.table.bah.cum{para,1};
ma2=sortresult.vltlt.table.ma.cum{para,2};
bah2=sortresult.vltlt.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,9);
plot(xlabel,bah2,xlabel,ma2);
%% lastmon
para =1;
ma1=sortresult.lastmon.table.ma.cum{para,1};
bah1=sortresult.lastmon.table.bah.cum{para,1};
ma2=sortresult.lastmon.table.ma.cum{para,2};
bah2=sortresult.lastmon.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,10);
plot(xlabel,bah2,xlabel,ma2);
para =2;
ma1=sortresult.lastmon.table.ma.cum{para,1};
bah1=sortresult.lastmon.table.bah.cum{para,1};
ma2=sortresult.lastmon.table.ma.cum{para,2};
bah2=sortresult.lastmon.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,11);
plot(xlabel,bah2,xlabel,ma2);
para =3;
ma1=sortresult.lastmon.table.ma.cum{para,1};
bah1=sortresult.lastmon.table.bah.cum{para,1};
ma2=sortresult.lastmon.table.ma.cum{para,2};
bah2=sortresult.lastmon.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,12);
plot(xlabel,bah2,xlabel,ma2);
%% sixmonth
para =1;
ma1=sortresult.sixmonth.table.ma.cum{para,1};
bah1=sortresult.sixmonth.table.bah.cum{para,1};
ma2=sortresult.sixmonth.table.ma.cum{para,2};
bah2=sortresult.sixmonth.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,13);
plot(xlabel,bah2,xlabel,ma2);
para =2;
ma1=sortresult.sixmonth.table.ma.cum{para,1};
bah1=sortresult.sixmonth.table.bah.cum{para,1};
ma2=sortresult.sixmonth.table.ma.cum{para,2};
bah2=sortresult.sixmonth.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,14);
plot(xlabel,bah2,xlabel,ma2);
para =3;
ma1=sortresult.sixmonth.table.ma.cum{para,1};
bah1=sortresult.sixmonth.table.bah.cum{para,1};
ma2=sortresult.sixmonth.table.ma.cum{para,2};
bah2=sortresult.sixmonth.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,15);
plot(xlabel,bah2,xlabel,ma2);
%% sixtymonth
para =1;
ma1=sortresult.sixtymonth.table.ma.cum{para,1};
bah1=sortresult.sixtymonth.table.bah.cum{para,1};
ma2=sortresult.sixtymonth.table.ma.cum{para,2};
bah2=sortresult.sixtymonth.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,16);
plot(xlabel,bah2,xlabel,ma2);
para =2;
ma1=sortresult.sixtymonth.table.ma.cum{para,1};
bah1=sortresult.sixtymonth.table.bah.cum{para,1};
ma2=sortresult.sixtymonth.table.ma.cum{para,2};
bah2=sortresult.sixtymonth.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,17);
plot(xlabel,bah2,xlabel,ma2);
para =3;
ma1=sortresult.sixtymonth.table.ma.cum{para,1};
bah1=sortresult.sixtymonth.table.bah.cum{para,1};
ma2=sortresult.sixtymonth.table.ma.cum{para,2};
bah2=sortresult.sixtymonth.table.bah.cum{para,2};
xlabel = [2003:2014]';
subplot(6,3,18);
plot(xlabel,bah2,xlabel,ma2);
end

